# Generated by Django 5.0.4 on 2024-06-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attendance_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='employee',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_status',
        ),
        migrations.AddField(
            model_name='attendance',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='Present', max_length=20),
        ),
    ]
