# Generated by Django 5.0.4 on 2024-06-26 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_attendance_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuereport',
            old_name='description',
            new_name='issue_description',
        ),
        migrations.RenameField(
            model_name='issuereport',
            old_name='submitted_at',
            new_name='reported_at',
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='account_number',
            new_name='bank_account_number',
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
