# Generated by Django 5.0.4 on 2024-06-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_description_issuereport_issue_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarydetail',
            name='total_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
