# Generated by Django 5.0.4 on 2024-06-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('company_benefits_opinion', models.TextField(blank=True, null=True)),
                ('improvement_ideas', models.TextField(blank=True, null=True)),
                ('satisfaction_rating', models.IntegerField()),
                ('anonymous_feedback', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
